#!/usr/bin/env ruby
# frozen_string_literal: true

require 'pathname'
require 'pry'

source_path = File.expand_path("#{Pathname.new(__FILE__).dirname}/../lib")
$LOAD_PATH << source_path

require 'rails_app_generator'

first = ARGV.first

if ARGV.empty?
  puts 'Please provide a profile for the new application'
  puts
  puts 'See --help for more info'
elsif %w[-v --version].include?(first)
  puts RailsAppGenerator::VERSION
elsif first == 'diff'
  RailsAppGenerator::Cli::Diff.start(ARGV)
elsif first == 'new'
  puts 'TODO: NEW'

  # # Use RAG with in the same way as the Rails generator (the following commands should be equivalent)
  # #   rails new args
  # #   rag   new args
  # if ARGV.first == 'new'
  #   # NOTE: This is not yet working
  #   RailsAppGenerator::Cli::Standard.start ARGV[1..]
  #   exit 0
  # elsif !ARGV.first.nil?
  # end

else
  fallback_profile_path = File.expand_path("#{Pathname.new(__FILE__).dirname}/../profiles")
  args = ['profile'] + ARGV + ["--fallback-profile-path=#{fallback_profile_path}"]

  RailsAppGenerator::Cli::Profile.start(args)
end

exit 0
