#!/usr/bin/env ruby
# frozen_string_literal: true

require 'pathname'

source_path = File.expand_path("#{Pathname.new(__FILE__).dirname}/../lib")
$LOAD_PATH << source_path

require 'rails_app_generator'

first = ARGV.first

if ARGV.empty?
  puts 'Please provide a profile for the new application'
  puts
  puts 'See --help for more info'
elsif %w[-v --version].include?(first)
  puts RailsAppGenerator::VERSION
elsif first == 'diff'
  RailsAppGenerator::Cli::Diff.start(ARGV)
elsif first == 'new'
  RailsAppGenerator::AppGenerator.start(ARGV[1..], destination_root: '/Users/davidcruwys/dev/kgems/rails_app_generator/a/rag')
else
  require 'rails_app_generator/rag_initializer'

  fallback_profile_path = File.expand_path("#{Pathname.new(__FILE__).dirname}/../profiles")
  args = ['profile'] + ARGV + ["--fallback-profile-path=#{fallback_profile_path}"]

  RailsAppGenerator::Cli::Profile.start(args)
end

exit 0
